import {chromium} from 'file:///C:/Users/dmkra/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
try{for(const before of [true,false]){
 const label=before?'before':'after';const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,locale:'en-US',recordVideo:{dir:'design/regressions-2026-09-21/video',size:{width:390,height:844}}});const p=await context.newPage();
 await p.route('**/*engine.ts*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('this.registerTools();','window.__qaEngine=this; this.registerTools();')});});
 await p.route('**/*inhabitant-animation.mjs*',async route=>{const response=await route.fetch();let body=await response.text();if(before)body=body.replace("if (['giant', 'hunter'].includes(s.id) && screenR >= 62) cache = false;",'');body+='\nwindow.__animationStats=animationCacheStats;';await route.fulfill({response,body});});
 await p.goto('http://127.0.0.1:5196/');await p.waitForFunction(()=>window.__qaEngine?.assetsReady);
 await p.evaluate(()=>{const e=window.__qaEngine;e.startTest(0,2,false,true,false);e.sound=false;e.setAudio();e.world.move=()=>{};const all=e.world.entities;const giant=all.find(f=>f.kind==='giant'),hunter=all.find(f=>f.kind==='hunter');if(!giant||!hunter)throw new Error('Missing microscope fixture');e.food=[{...giant,x:e.life.x-85,y:e.life.y-150,r:90,eaten:false,seed:1,attack:0,escape:0},{...hunter,x:e.life.x+65,y:e.life.y+160,r:74,eaten:false,seed:2,attack:0,escape:0}];e.world.entities=e.food;e.life.x=700;e.life.y=970;e.camera={x:700,y:970};e.particles=[];e.hint='';e.publish();const render=e.render.bind(e);window.drawTimes=[];e.render=()=>{const s=performance.now();render();window.drawTimes.push(performance.now()-s);};});
 await p.waitForTimeout(7000);const metrics=await p.evaluate(()=>{const a=window.drawTimes.sort((a,b)=>a-b);return{cache:window.__animationStats(),renderP95:a[Math.floor(a.length*.95)],frames:a.length}});results.push({label,...metrics});await p.screenshot({path:`design/regressions-2026-09-21/micro-${label}.png`});const video=p.video();await context.close();await video.saveAs(`design/regressions-2026-09-21/micro-${label}.webm`);
}}finally{await browser.close();}fs.writeFileSync('design/regressions-2026-09-21/micro.json',JSON.stringify(results,null,2));console.log(results);
