import {chromium} from 'file:///C:/Users/dmkra/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'chrome',headless:true});const context=await b.newContext({viewport:{width:430,height:932},deviceScaleFactor:2,isMobile:true,hasTouch:true});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
// Test-only observation hook in the served module; repository source has no debug global.
await p.route('**/app/engine.ts',async route=>{const r=await route.fetch();const text=await r.text();await route.fulfill({response:r,body:text.replace('this.registerTools();','window.__qaEngine=this; this.registerTools();')});});
await p.goto('http://127.0.0.1:5194/');await p.waitForFunction(()=>window.__qaEngine?.assetsReady);await p.waitForTimeout(500);
const shot=async name=>{await p.waitForTimeout(350);await p.screenshot({path:`design/final-ui-2026-09-19/${name}.png`});};
await shot('development-intro');await p.getByRole('button',{name:'Pasar a UI final'}).click();await shot('final-intro');assert.equal(await p.locator('main').getAttribute('data-ui-mode'),'final');
await p.getByRole('button',{name:'Configuración',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Mostrar rendimiento'}).count(),0);assert.equal(await p.getByRole('button',{name:'Probar entornos y tamaños'}).count(),0);await shot('final-settings');
await p.getByRole('button',{name:'Volver a UI de desarrollo'}).click();assert.equal(await p.getByRole('button',{name:'Mostrar rendimiento'}).count(),1);await shot('development-settings');
await p.getByRole('button',{name:'Volver al juego',exact:true}).click();await p.evaluate(()=>{__qaEngine.startTest(0,2,false,true,false);__qaEngine.world.move=()=>{};});await p.waitForTimeout(1500);await shot('development-hud');
await p.getByRole('button',{name:'Configuración',exact:true}).click();const before=await p.evaluate(()=>({stage:__qaEngine.progress.stage,mass:__qaEngine.life.biomass,xp:__qaEngine.progress.xp,x:__qaEngine.life.x,y:__qaEngine.life.y}));await p.getByRole('button',{name:'Pasar a UI final'}).click();const after=await p.evaluate(()=>({stage:__qaEngine.progress.stage,mass:__qaEngine.life.biomass,xp:__qaEngine.progress.xp,x:__qaEngine.life.x,y:__qaEngine.life.y}));assert.deepEqual(after,before);
await p.getByRole('button',{name:'Volver al juego',exact:true}).click();await shot('final-hud');assert.equal(await p.getByRole('group',{name:'Zoom de cámara'}).count(),0);
await p.getByRole('button',{name:'Pausar',exact:true}).click();await shot('final-pause');await p.getByRole('button',{name:'Continuar',exact:true}).click();
await p.evaluate(()=>__qaEngine.boostTest('adaptation'));await p.waitForTimeout(1200);await shot('final-adaptation');const box=await p.locator('.adaptation-bubble').first().boundingBox();await p.mouse.click(box.x+box.width/2,box.y+box.height/2);await p.waitForTimeout(500);
await p.evaluate(()=>{__qaEngine.life.dead=true;__qaEngine.publish();});await shot('final-death');await p.getByRole('button',{name:'Reintentar',exact:true}).click();
await p.evaluate(()=>{__qaEngine.startTest(9,230,false,true,true);__qaEngine.beginUniverseFinale();__qaEngine.update(17);});await shot('final-survivor');await p.getByRole('button',{name:'Pausar',exact:true}).click();await shot('final-survivor-pause');assert.equal(await p.getByRole('button',{name:'Continuar',exact:true}).count(),1);await p.getByRole('button',{name:'Continuar',exact:true}).click();
await p.getByRole('button',{name:'Configuración',exact:true}).click();await p.getByText('Créditos musicales',{exact:true}).click();await p.getByText('Créditos musicales',{exact:true}).scrollIntoViewIfNeeded();await shot('final-credits');assert.equal(await p.locator('.music-credits li a').count(),12);
await p.reload();await p.waitForFunction(()=>window.__qaEngine?.assetsReady);assert.equal(await p.locator('main').getAttribute('data-ui-mode'),'final');
const responsive=[];for(const [width,height] of [[360,740],[768,1024]]){await p.setViewportSize({width,height});await shot(`final-intro-${width}`);responsive.push({width,overflow:await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth)});}
const result={errors,progressPreserved:JSON.stringify(before)===JSON.stringify(after),modePersists:true,credits:12,responsive};assert.equal(errors.length,0);assert.ok(responsive.every(r=>!r.overflow));fs.writeFileSync('design/final-ui-2026-09-19/browser.json',JSON.stringify(result,null,2));console.log(result);await context.close();await b.close();
